// Batch E — the mezuzah in a real home: small rooms, the parking, the lift, the shelter, the balcony, one blessing,
// paint, a mezuzah that fell, a metal door.
import { E, span, write, OWNER } from './lib.mjs';
const Y = n => `yalkut-yosef-${n}`;
const M = { place: 'family', topic: 'מזוזה וחנוכת בית', contexts: ['home'] };
write('e-home', [
  E({ ...M, id: 'hal-prk-mezuzah-small-room', subtopic: 'איזה חדר חייב',
    sectionId: Y('58-2-8'), excerpt: span(Y('58-2-8'), "חדר שאין בו ד' אמות על ד' אמות פטור ממזוזה", 'צריך לקבוע מזוזה בלי ברכה).'),
    question: 'יש לי חדר קטן מאוד (מזווה, ארון קיר גדול) – צריך בו מזוזה?',
    shortAnswer: 'חדר שאין בו ארבע אמות על ארבע אמות – כ־1.96 מטר על 1.96 מטר – פטור ממזוזה. בין 1.92 ל־1.96 מטר קובעים מזוזה בלי ברכה.',
    ruleType: 'din', conditions: ['חדר צר וארוך שיש בו שטח של ארבע אמות על ארבע אמות – יש לו דין משלו.'],
    variants: ['מזוזה בחדר קטן', 'מזוזה במזווה', 'ארון קיר מזוזה', 'חדר קטן פטור ממזוזה', 'מזוזה בחדר שירות קטן'],
    searchTerms: ['מזוזה', 'ארבע אמות', 'חדר קטן', 'מזווה'], tags: ['מזוזה', 'שיעורים'],
    related: ['hal-prk-mezuzah-balcony'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-parking', subtopic: 'איזה חדר חייב',
    sectionId: Y('58-2-34'), excerpt: span(Y('58-2-34'), 'חדר המיועד לחניית רכב', 'אלא יקבענה בלי ברכה.'),
    question: 'צריך מזוזה בחניה מקורה או במוסך הפרטי?',
    shortAnswer: 'יש מי שכתב שחדר חניה מקורה עם שער ודלת חייב במזוזה, ולדעת הרמב"ם גם אז פטור. לכן קובעים שם מזוזה בלי ברכה.',
    ruleType: 'machloket', dispute: 'יש מחייבים חניה מקורה עם דלת, ולדעת הרמב"ם פטורה; לכן קובעים בלי ברכה.',
    conditions: [],
    variants: ['מזוזה בחניה', 'מזוזה במוסך', 'מזוזה בחניון הבית', 'חניה מקורה מזוזה בברכה'],
    searchTerms: ['מזוזה', 'חניה', 'מוסך', 'חניון'], tags: ['מזוזה', 'בלי ברכה'],
    related: ['hal-prk-mezuzah-shelter-storage'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-elevator', subtopic: 'איזה חדר חייב',
    sectionId: Y('58-2-35'), excerpt: span(Y('58-2-35'), 'מעלית, יש אומרים שאינה חייבת במזוזה', 'והמחמיר לקבוע שם מזוזה בלי ברכה, תבוא עליו ברכה.'),
    question: 'צריך מזוזה במעלית או בפתח שנכנסים ממנו למעלית?',
    shortAnswer: 'המנהג כדעת האומרים שמעלית פטורה ממזוזה, וכך גם הפתח שבבניין שדרכו נכנסים אליה. והמחמיר לקבוע בה מזוזה בלי ברכה – תבוא עליו ברכה.',
    ruleType: 'minhag', conditions: [],
    variants: ['מזוזה במעלית', 'מעלית חייבת מזוזה', 'פתח המעלית מזוזה'],
    searchTerms: ['מזוזה', 'מעלית'], tags: ['מזוזה', 'מעלית'],
    related: [], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-shelter-storage', subtopic: 'איזה חדר חייב',
    sectionId: Y('58-2-14'), excerpt: span(Y('58-2-14'), 'מקלט המשמש גם כמחסן חייב במזוזה', 'פטור ממזוזה לגמרי.'),
    question: 'צריך מזוזה בממ"ד, במקלט או במחסן?',
    shortAnswer: 'מקלט שמשמש גם כמחסן חייב במזוזה, ואת הברכה מברכים על המזוזה הראשונה בבית ופוטרים בה גם אותו. מקלט שאין משתמשים בו לשום דבר אחר – פטור לגמרי.',
    ruleType: 'din', conditions: [],
    variants: ['מזוזה בממד', 'מזוזה במקלט', 'מזוזה במחסן', 'מקלט בבניין מזוזה'],
    searchTerms: ['מזוזה', 'ממ"ד', 'ממד', 'מקלט', 'מחסן'], tags: ['מזוזה', 'מחסן', 'מקלט'],
    related: ['hal-prk-mezuzah-one-blessing'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-balcony', subtopic: 'איזה חדר חייב',
    sectionId: Y('58-2-17'), excerpt: span(Y('58-2-17'), 'מרפסות וגזוזטראות שאינן מקורות', 'המחמיר לקבוע מזוזה בלי ברכה תבא עליו ברכה.'),
    question: 'צריך מזוזה ביציאה למרפסת?',
    shortAnswer: 'מרפסת שאין לה כניסה אלא דרך הדירה, ואין בה ארבע אמות על ארבע אמות – אינה צריכה מזוזה מן הדין, וכל שכן כשאינה מקורה. והמחמיר לקבוע בלי ברכה – תבוא עליו ברכה.',
    ruleType: 'din', conditions: ['מרפסת בקומת קרקע שנכנסים דרכה מהרחוב – דינה אחר.'],
    variants: ['מזוזה במרפסת', 'מזוזה ביציאה למרפסת', 'מרפסת שמש מזוזה', 'מזוזה בדלת הזזה למרפסת'],
    searchTerms: ['מזוזה', 'מרפסת', 'גזוזטרא'], tags: ['מזוזה', 'מרפסת'],
    related: ['hal-prk-mezuzah-small-room'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-one-blessing', subtopic: 'ברכה',
    sectionId: Y('58-3-21'), excerpt: span(Y('58-3-21'), 'המנהג פשוט שמברכים רק על המזוזה שקובעים בפתח הבית', 'ברכה אחת לכולן.'),
    question: 'אני קובע כמה מזוזות בבית – מברכים על כל אחת?',
    shortAnswer: 'לא. המנהג לברך פעם אחת, על המזוזה שבפתח הבית, ולפטור בה את כל מזוזות החדרים; ברכה על כל מזוזה היא ברכה שאינה צריכה.',
    ruleType: 'minhag', conditions: ['אם יש הפסק ממשי באמצע, כמו הליכה לדירה אחרת – ראו הדינים הסמוכים.'],
    variants: ['ברכה על כל מזוזה', 'כמה ברכות על מזוזות', 'קביעת מזוזות בכל הבית ברכה אחת'],
    searchTerms: ['מזוזה', 'ברכה', 'לקבוע מזוזה'], tags: ['מזוזה', 'ברכה'],
    related: ['hal-bayit-mezuzah-blessing'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-painted', subtopic: 'בדיקה',
    sectionId: Y('58-3-35'), excerpt: span(Y('58-3-35'), 'אם לא הסירו את המזוזות קודם הצביעה', 'ונתקלקלו האותיות.'),
    question: 'צבעו את הבית ולא הורידו את המזוזות – מה צריך לעשות?',
    shortAnswer: 'צריך לבדוק את המזוזות, כי ייתכן שנכנסה אליהן לחות והאותיות התקלקלו.',
    ruleType: 'din', conditions: [],
    variants: ['צבעו על המזוזה', 'צביעת הבית ומזוזות', 'שיפוץ ומזוזות', 'מזוזה אחרי צבע'],
    searchTerms: ['מזוזה', 'צבע', 'צביעה', 'שיפוץ', 'בדיקת מזוזות'], tags: ['מזוזה', 'בדיקה'],
    related: ['hal-bayit-mezuzah-checking'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-dropped', subtopic: 'בדיקה',
    sectionId: Y('58-3-46'), excerpt: span(Y('58-3-46'), 'מי שנפלה מזוזה מידו על הארץ', 'אם הם כשרים.'),
    question: 'המזוזה נפלה לי מהיד על הרצפה – צריך לצום?',
    shortAnswer: 'אין צריך להתענות. טוב לתת מעות לצדקה, ונכון גם לבדוק אם שאר מזוזות הבית כשרות.',
    ruleType: 'din', conditions: [],
    variants: ['מזוזה נפלה על הרצפה', 'הפלתי מזוזה', 'צום על מזוזה שנפלה', 'נפלה לי מזוזה מה עושים'],
    searchTerms: ['מזוזה', 'נפלה', 'תענית', 'צדקה'], tags: ['מזוזה', 'צדקה'],
    related: ['hal-prk-mezuzah-refix-blessing'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-refix-blessing', subtopic: 'ברכה',
    sectionId: Y('58-3-29'), excerpt: span(Y('58-3-29'), 'אם נפלה המזוזה מעצמה ממזוזת הפתח', 'וספק ברכות להקל.'),
    question: 'המזוזה נפלה מהפתח ואני מחזיר אותה – מברכים שוב?',
    shortAnswer: 'יש בזה מחלוקת, ולכן לא מברכים – ספק ברכות להקל.',
    ruleType: 'machloket', dispute: 'נחלקו אם מברכים על קביעה חוזרת של מזוזה שנפלה; ספק ברכות להקל.',
    conditions: ['מזוזה שנפלה בשבת – יש לה דינים מיוחדים.'],
    variants: ['להחזיר מזוזה שנפלה ברכה', 'מזוזה נפלה מהמשקוף', 'קביעת מזוזה מחדש בברכה'],
    searchTerms: ['מזוזה', 'נפלה', 'ברכה', 'קביעה מחדש'], tags: ['מזוזה', 'ספק ברכות'],
    related: ['hal-prk-mezuzah-dropped'], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-metal-door', subtopic: 'אופן הקביעה',
    sectionId: Y('58-3-18'), excerpt: span(Y('58-3-18'), 'מזוזה שאין כל אפשרות לקובעה בפתח על ידי מסמרים', 'פסולה,'),
    question: 'המשקוף מברזל ואי אפשר לדפוק מסמרים – מותר להדביק את המזוזה?',
    shortAnswer: 'כן, בדבק חזק שמחזיק אותה ביציבות לאורך זמן – זה נחשב חיבור גמור. אבל מזוזה שתלויה ומתנדנדת – פסולה.',
    ruleType: 'din', conditions: [],
    variants: ['להדביק מזוזה', 'מזוזה בדבק דו צדדי', 'דלת ברזל מזוזה', 'מזוזה על משקוף מתכת'],
    searchTerms: ['מזוזה', 'דבק', 'מסמרים', 'ברזל', 'מתכת'], tags: ['מזוזה', 'קביעה'],
    related: [], discovery: [OWNER] }),

  E({ ...M, id: 'hal-prk-mezuzah-back-from-trip', subtopic: 'ברכה',
    sectionId: Y('58-3-55'), excerpt: span(Y('58-3-55'), 'היוצא מביתו ונוסע לעיר אחרת לחודש ימים', 'אין הבית נפקע מחיוב מזוזה,'),
    question: 'חזרנו הביתה אחרי חודש בחו"ל – צריך לברך שוב על המזוזות?',
    shortAnswer: 'לא. מי שנסע עם כל בני ביתו לזמן ודעתו לחזור – הבית לא יצא מחיוב מזוזה, ואין מברכים שוב כשחוזרים.',
    ruleType: 'din', conditions: [],
    variants: ['חזרנו מחופשה מזוזה ברכה', 'אחרי חודש בחוץ לארץ מזוזות', 'בית ריק חודש מזוזה'],
    searchTerms: ['מזוזה', 'חופשה', 'נסיעה', 'ברכה'], tags: ['מזוזה', 'נסיעה'],
    related: [], discovery: [OWNER] }),
]);
