// Builds src/data/halachaSourceMap.mjs: for each verified entry, the Shulchan Arukh siman its Yalkut Yosef section is
// built on — only where that is verified by the texts themselves, not assumed from numbering.
//   1. The siman number is read from the Yalkut Yosef section header ("סימן רב - …").
//   2. The book follows the Yalkut Yosef part (Orach Chayim / Yoreh De'ah).
//   3. Verification: the Yalkut section's wording is compared (IDF-weighted shared words) with every se'if of the whole
//      book. The link is kept only if the claimed siman is among the 3 closest simanim of the book and its best se'if
//      shares enough distinctive wording. That se'if is stored as the closest parallel passage ("לעיון").
// Usage: node scripts/halacha/source-map.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const ROOT = new URL('../../', import.meta.url).pathname;
const { YALKUT_YOSEF } = await import(`${ROOT}src/data/yalkutYosef.mjs`);
const { PRACTICAL_HALACHA_QA } = await import(`${ROOT}src/data/practicalHalachaQa.mjs`);

const LETTERS = { א: 1, ב: 2, ג: 3, ד: 4, ה: 5, ו: 6, ז: 7, ח: 8, ט: 9, י: 10, כ: 20, ך: 20, ל: 30, מ: 40, ם: 40, נ: 50, ן: 50, ס: 60, ע: 70, פ: 80, ף: 80, צ: 90, ץ: 90, ק: 100, ר: 200, ש: 300, ת: 400 };
const gematria = word => [...word.replace(/["'׳״]/g, '')].reduce((sum, ch) => sum + (LETTERS[ch] || 0), 0);
const plain = text => String(text || '').replace(/[֑-ׇ]/g, '').replace(/[^א-ת\s]/g, ' ').replace(/\s+/g, ' ').trim();
const STOP = new Set('של את על אם או לא כל זה זו הוא היא הם הן אבל גם כי אין יש עד אחר כמו כן שם אלא לו לה בו בה מה מי כדי אף וכן ואם ואין שלא'.split(' '));
const words = text => [...new Set(plain(text).split(' ').filter(word => word.length >= 3 && !STOP.has(word)).map(word => word.replace(/^[והבלמשכ](?=.{3,})/, '')))];

function simanFromHeader(header) {
  const match = String(header).match(/^סימן\s+([א-ת"'׳״]+)(?:\s*[-,]\s*([א-ת"'׳״]+))?/);
  if (!match) return [];
  return [match[1], match[2]].filter(Boolean).map(gematria).filter(n => n > 0 && n < 700);
}
const bookForPart = part => (part >= 2 && part <= 36 ? 'Orach_Chayim' : part >= 39 && part <= 66 ? 'Yoreh_Deah' : null);
const BOOK_HE = { Orach_Chayim: 'אורח חיים', Yoreh_Deah: 'יורה דעה' };
const BOOK_REF = { Orach_Chayim: 'Shulchan Arukh, Orach Chayim', Yoreh_Deah: "Shulchan Arukh, Yoreh De'ah" };

const books = {};
for (const book of Object.keys(BOOK_HE)) {
  const json = JSON.parse(readFileSync(`${ROOT}public/library/packs/sefaria-shulchan-arukh-pd/Shulchan_Arukh__${book}.json`, 'utf8'));
  const seifim = json.nodes.flatMap(node => node.units.map(unit => ({ siman: node.n, seif: unit.n, text: unit.text, words: words(unit.text) })));
  const df = new Map();
  for (const seif of seifim) for (const word of seif.words) df.set(word, (df.get(word) || 0) + 1);
  const idf = word => Math.log(seifim.length / (1 + (df.get(word) || 0)));
  books[book] = { seifim, idf };
}

const sections = new Map(YALKUT_YOSEF.sections.map(section => [section.id, section]));
const map = {};
const stats = { entries: 0, candidates: 0, verified: 0, rejected: 0, noHeader: 0 };
for (const entry of PRACTICAL_HALACHA_QA) {
  const sourceId = entry.sources?.[0]?.localSourceId;
  const section = sections.get(sourceId);
  if (!section) continue;
  stats.entries++;
  const book = bookForPart(section.part);
  const simanim = simanFromHeader(section.section);
  if (!book || !simanim.length) { stats.noHeader++; continue; }
  stats.candidates++;
  const { seifim, idf } = books[book];
  const mine = new Set(words(section.text));
  const score = seif => seif.words.reduce((sum, word) => sum + (mine.has(word) ? idf(word) : 0), 0);
  const bestBySiman = new Map();
  for (const seif of seifim) { const s = score(seif); const best = bestBySiman.get(seif.siman); if (!best || s > best.score) bestBySiman.set(seif.siman, { seif, score: s }); }
  const ranking = [...bestBySiman.entries()].sort((a, b) => b[1].score - a[1].score);
  const claimed = simanim.map(n => ({ n, rank: ranking.findIndex(([siman]) => siman === n) + 1, best: bestBySiman.get(n) })).filter(item => item.best).sort((a, b) => a.rank - b.rank)[0];
  if (process.env.DEBUG_MAP && claimed) console.log("DBG", claimed.rank, Math.round(claimed.best.score));
  if (!claimed || claimed.rank > 3 || claimed.best.score < 18) { stats.rejected++; continue; }
  stats.verified++;
  map[entry.id] = { book, bookHe: BOOK_HE[book], siman: claimed.n, seif: claimed.best.seif.seif, rank: claimed.rank, ref: `${BOOK_REF[book]} ${claimed.n}:${claimed.best.seif.seif}`, simanRef: `${BOOK_REF[book]} ${claimed.n}`, text: claimed.best.seif.text };
}

writeFileSync(`${ROOT}src/data/halachaSourceMap.mjs`, `// Generated by scripts/halacha/source-map.mjs — do not edit by hand.
// entryId → the Shulchan Arukh siman its Yalkut Yosef section is built on, verified by wording (see the script), and the
// closest se'if in that siman, for study. It is a parallel for learning, not the source of the app's practical ruling.
export const SOURCE_MAP_STATS = ${JSON.stringify(stats)};
export const HALACHA_SOURCE_MAP = ${JSON.stringify(map)};
`);
console.log(stats);
