// שלום רב — the author's book of prayers, segulot, blessings and words of strengthening, as a library: by topic, by
// need, in the book's own order, searchable, with the names the book leaves blank filled in on screen only. Pure.
// The text is src/data/shalomRav/book.mjs (generated by scripts/shalom-rav/build.mjs from the verified extraction of the
// supplied PDF); it is loaded on first use as its own chunk and works offline.

export const loadShalomRav = () => import('../data/shalomRav/book.mjs').then(module => module.default);

export const shalomRavRoute = {
  home: () => 'shalom-rav',
  byBook: () => 'shalom-rav/book',
  need: key => `shalom-rav/need/${key}`,
  category: key => `shalom-rav/c/${key}`,
  entry: (id, anchor) => `shalom-rav/e/${id}${anchor ? `/${anchor}` : ''}`,
};

// shalom-rav | shalom-rav/book | shalom-rav/need/<key> | shalom-rav/c/<key> | shalom-rav/e/<id>[/<anchor>]
export function parseShalomRavRoute(route) {
  const parts = String(route || '').split('/');
  if (parts[0] !== 'shalom-rav') return null;
  if (parts[1] === 'e' && parts[2]) return { view: 'entry', id: decodeURIComponent(parts[2]), anchor: parts[3] ? decodeURIComponent(parts[3]) : null };
  if (parts[1] === 'need' && parts[2]) return { view: 'need', key: parts[2] };
  if (parts[1] === 'c' && parts[2]) return { view: 'category', key: parts[2] };
  if (parts[1] === 'book') return { view: 'book' };
  return { view: 'home' };
}

// A TOC target "brit-mila#sandak" opens the entry at its section.
export function tocRoute(target) {
  const [id, anchor] = String(target).split('#');
  return shalomRavRoute.entry(id, anchor);
}

export const entryById = (book, id) => book.entries.find(entry => entry.id === id) || null;
export const readableEntries = book => book.entries.filter(entry => entry.category !== 'about');
export const entriesInCategory = (book, key) => readableEntries(book).filter(entry => entry.category === key);
export const entriesForNeed = (book, key) => readableEntries(book).filter(entry => (entry.needs || []).includes(key));

// The book is read in its own order: the previous and next entry (the introduction and the closing words included).
export function neighbours(book, id) {
  const list = book.entries;
  const i = list.findIndex(entry => entry.id === id);
  return { previous: i > 0 ? list[i - 1] : null, next: i >= 0 && i < list.length - 1 ? list[i + 1] : null };
}

// Related entries: those that share a need with it, the closest in the book first. Curated, never generated.
export function relatedEntries(book, entry, limit = 4) {
  if (!entry?.needs?.length) return [];
  return readableEntries(book)
    .filter(other => other.id !== entry.id && other.needs?.some(need => entry.needs.includes(need)))
    .map(other => ({ other, shared: other.needs.filter(need => entry.needs.includes(need)).length }))
    .sort((a, b) => b.shared - a.shared || Math.abs(a.other.order - entry.order) - Math.abs(b.other.order - entry.order))
    .slice(0, limit)
    .map(item => item.other);
}

// Search text: letters only — points, cantillation, punctuation and final forms folded away.
const FINALS = { ך: 'כ', ם: 'מ', ן: 'נ', ף: 'פ', ץ: 'צ' };
export const foldHebrew = text => String(text || '')
  .replace(/[֑-ׇ]/g, '')
  .replace(/[״”“"׳’‘'`]/g, '')
  .replace(/[ךםןףץ]/g, ch => FINALS[ch])
  .replace(/[^א-ת0-9a-z\s]/gi, ' ')
  .replace(/\s+/g, ' ')
  .trim();

// Deterministic search over the book: a title outranks a need or a category, which outrank an attribution, an
// explanation and finally the text itself. Every query word must be found somewhere in the entry.
export function searchShalomRav(book, query, { limit = 12 } = {}) {
  const words = foldHebrew(query).split(' ').filter(word => word.length > 1);
  if (!words.length) return [];
  const needTitle = Object.fromEntries(book.needs.map(need => [need.key, need.title]));
  const categoryTitle = Object.fromEntries(book.categories.map(category => [category.key, category.title]));
  const results = [];
  for (const entry of book.entries) {
    const fields = [
      [8, [entry.title, entry.printedTitle, entry.tocTitle, entry.subtitle].filter(Boolean).join(' ')],
      [5, [...(entry.needs || []).map(key => needTitle[key]), categoryTitle[entry.category], ...(entry.keywords || [])].filter(Boolean).join(' ')],
      [4, [entry.attributedTo, ...entry.blocks.filter(block => block.type === 'section').map(block => block.title)].filter(Boolean).join(' ')],
      [2, entry.blocks.filter(block => block.type === 'explanation' || block.type === 'instruction').map(block => block.text).join(' ')],
      [1, entry.blocks.filter(block => block.type === 'text' || block.type === 'source').map(block => block.text).join(' ')],
    ].map(([weight, text]) => [weight, ` ${foldHebrew(text)} `]);
    let score = 0;
    let all = true;
    for (const word of words) {
      const hit = fields.filter(([, text]) => text.includes(word));
      if (!hit.length) { all = false; break; }
      score += Math.max(...hit.map(([weight, text]) => weight + (text.includes(` ${word} `) ? 1 : 0)));
    }
    if (!all) continue;
    const where = fields.find(([weight, text]) => weight <= 2 && words.every(word => text.includes(word)));
    results.push({ entry, score, snippet: where && fields[0][1].indexOf(words[0]) < 0 ? snippetFor(entry, words) : '' });
  }
  return results.sort((a, b) => b.score - a.score || a.entry.order - b.entry.order).slice(0, limit);
}

function snippetFor(entry, words) {
  for (const block of entry.blocks) {
    if (!block.text) continue;
    const folded = foldHebrew(block.text);
    const at = folded.indexOf(words[0]);
    if (at < 0) continue;
    const plain = block.text.replace(/[֑-ׇ]/g, '');
    const start = Math.max(0, Math.round(at * plain.length / Math.max(folded.length, 1)) - 30);
    return `${start ? '…' : ''}${plain.slice(start, start + 90).trim()}…`;
  }
  return '';
}

// Personalization is presentation only: the stored text never changes. Each placeholder occurrence is replaced by
// the person the entry assigns to it (by its order of appearance when the book repeats the same placeholder for two
// people). A person's name is written with the connective the reader chose (בן / בת) — never guessed; with no name
// yet, the book's own placeholder stays.
export function personName(person, value) {
  if (!value) return '';
  if (person.kind === 'city' || person.kind === 'name' || !person.mother) return String(value.name || '').trim();
  const name = String(value.name || '').trim();
  const mother = String(value.mother || '').trim();
  if (!name) return '';
  if (!mother) return name;
  return `${name} ${value.link || 'בן/בת'} ${mother}`;
}

// Split a text into plain parts and placeholders: [{ text }, { placeholder, person, filled }].
export function personalize(text, personalization, values = {}, counters = {}) {
  if (!personalization?.placeholders?.length) return [{ text }];
  const people = Object.fromEntries(personalization.people.map(person => [person.key, person]));
  const tokens = [...new Set(personalization.placeholders.map(item => item.token))].sort((a, b) => b.length - a.length);
  const out = [];
  let rest = String(text);
  while (rest) {
    let best = null;
    for (const token of tokens) {
      const at = rest.indexOf(token);
      if (at >= 0 && (!best || at < best.at)) best = { token, at };
    }
    if (!best) { out.push({ text: rest }); break; }
    if (best.at) out.push({ text: rest.slice(0, best.at) });
    counters[best.token] = (counters[best.token] || 0) + 1;
    const rules = personalization.placeholders.filter(item => item.token === best.token);
    const rule = rules.find(item => item.nth === counters[best.token]) || rules.find(item => !item.nth) || rules[rules.length - 1];
    const person = people[rule.person];
    out.push({ placeholder: best.token, person: rule.person, label: person?.label, filled: person ? personName(person, values[rule.person]) : '' });
    rest = rest.slice(best.at + best.token.length);
  }
  return out;
}

// Inline structure of a text: book instructions in parentheses and square brackets are shown quietly beside the
// words to be said (the words themselves are never altered).
export function inlineParts(text) {
  const parts = [];
  const re = /(\([^()]*\)|\[[^\[\]]*\])/g;
  let last = 0;
  for (const match of String(text).matchAll(re)) {
    if (match.index > last) parts.push({ text: text.slice(last, match.index) });
    parts.push({ text: match[0], aside: true });
    last = match.index + match[0].length;
  }
  if (last < String(text).length) parts.push({ text: String(text).slice(last) });
  return parts;
}
