// Where the Torah content engine (torahContent.mjs) reads its data in the app: the archive's index and search fields as
// modules generated by the ingestion (src/data/torahContent/*.mjs — each its own lazy chunk, and simply absent until the
// archive is in the build), the article bodies as packs beside the app (public/torah-content/packs/<pack>.json.gz).
// Nothing here is fetched from the network: the packs ship with the app.
import { checksum } from './prayer/checksum.mjs';
import { packBytesToText } from './library/packs.mjs';

const base = () => { try { return import.meta.env?.BASE_URL || '/'; } catch { return '/'; } };

// Vite resolves these at build time; a file that does not exist yields no entry (and outside Vite there is none).
let indexModules = {};
let searchModules = {};
try { indexModules = import.meta.glob('../data/torahContent/index.mjs'); } catch { indexModules = {}; }
try { searchModules = import.meta.glob('../data/torahContent/search.mjs'); } catch { searchModules = {}; }
const firstModule = async modules => { const load = Object.values(modules)[0]; return load ? (await load()).default : null; };

let manifest = null;
async function packManifest() {
  if (!manifest) manifest = fetch(`${base()}torah-content/packs/manifest.json`).then(response => (response.ok ? response.json() : null)).catch(() => null);
  return manifest;
}

/** Where the manifest says the search file is: { file (relative to torah-content/), checksum }. */
export function searchEntry(manifest) {
  const inPacks = !manifest?.search && !manifest?.files?.search && manifest?.packs?.search;
  const entry = manifest?.search || manifest?.files?.search || manifest?.packs?.search || null;
  const name = String(entry?.file || 'search.json.gz').replace(/^(?:\.\.\/)+/, '');
  const file = inPacks ? `packs/${name}` : name;
  return { file, checksum: entry?.checksum || null };
}

const appSource = {
  loadIndex: () => firstModule(indexModules),
  // The search fields: the gzipped file beside the packs (public/torah-content/search.json.gz, its checksum in the
  // manifest), else the older generated module (src/data/torahContent/search.mjs), else none (titles and metadata only).
  async loadSearch() {
    const listed = searchEntry(await packManifest());
    try {
      const response = await fetch(`${base()}torah-content/${listed.file}${listed.checksum ? `?v=${listed.checksum}` : ''}`);
      if (response.ok) {
        const text = await packBytesToText(new Uint8Array(await response.arrayBuffer()));
        if (listed.checksum && checksum(text) !== listed.checksum) throw new Error('search checksum');
        const data = JSON.parse(text);
        if (Array.isArray(data?.docs)) return data;
      }
    } catch { /* fall back to the module */ }
    return firstModule(searchModules);
  },
  async loadPack(name, entry) {
    let target = entry;
    if (!target.checksum) { const listed = (await packManifest())?.packs?.[name]; if (listed) target = { ...entry, ...listed }; }
    const response = await fetch(`${base()}torah-content/packs/${target.file}${target.checksum ? `?v=${target.checksum}` : ''}`);
    if (!response.ok) throw new Error('דבר התורה אינו זמין כרגע במכשיר.');
    const text = await packBytesToText(new Uint8Array(await response.arrayBuffer()));
    if (target.checksum && checksum(text) !== target.checksum) throw new Error('חבילת דברי התורה אינה תואמת לחתימה שלה ולכן לא נפתחה.');
    return JSON.parse(text);
  },
};

// Development only (VITE_TORAH_FIXTURE=1 npm run dev): the hand-made test fixture, to see the screens before the archive
// lands. The branch is removed from every build, and the fixture never ships.
// (`import.meta.env.DEV` is `false` in every build, and the module's name is not visible to the bundler: nothing of the
// fixture can reach a build, not even as an asset.)
const DEV_FIXTURE = ['.', 'torahContentDevFixture.mjs'].join('/');
const devFixture = (() => { try { return import.meta.env.DEV && import.meta.env.VITE_TORAH_FIXTURE === '1'; } catch { return false; } })();
const source = devFixture ? { lazy: () => import(/* @vite-ignore */ DEV_FIXTURE).then(module => module.default) } : null;
export default source ? {
  loadIndex: async () => (await source.lazy()).loadIndex(),
  loadSearch: async () => (await source.lazy()).loadSearch(),
  loadPack: async (name, entry) => (await source.lazy()).loadPack(name, entry),
} : appSource;
