#!/usr/bin/env node
// האתגר העולמי — writes the schedule of the days' five questions and the server's answer key, from the quiz bank.
//
//   node scripts/challenge/build-key.mjs                 extend the schedule to 450 days from today (append-only)
//   node scripts/challenge/build-key.mjs --until=2028-06-30
//   node scripts/challenge/build-key.mjs --check         verify, write nothing (exit 1 on a problem)
//
// Writes:
//   src/data/globalChallenge/schedule.mjs     date → the five question ids (the app; no answers in it)
//   server/challenge-worker/src/key.mjs       date → [[id, answer, difficulty] × 5] (the server only)
// Append-only: a day already scheduled is never changed, so every version of the app asks the same five on a day. A new
// day is chosen by services/globalChallenge/select.mjs pickDailySet (seeded by the date, five areas, the difficulties
// 1·1·2·2·3), avoiding the questions of the previous 60 scheduled days. Saturdays are left out (never a challenge);
// Yom Tov differs between Israel and the diaspora, so those days are scheduled and closed by the calendar instead.
//
// --check: every scheduled id is in the bank (valid), the key matches the bank's answers and difficulties exactly, the
// key and the schedule hold the same days, and the schedule reaches at least 120 days ahead (so it is extended long
// before it runs out). Question content is never changed here.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';
import { loadBank } from '../../src/services/quiz/bank.mjs';
import { pickDailySet } from '../../src/services/globalChallenge/select.mjs';
import { GLOBAL_SIZE } from '../../src/services/globalChallenge/scoring.mjs';
import { shiftDateKey, weekdayOf, isDateKey, keyOfUTC } from '../../src/services/globalChallenge/calendar.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const SCHEDULE_FILE = path.join(ROOT, 'src/data/globalChallenge/schedule.mjs');
export const KEY_FILE = path.join(ROOT, 'server/challenge-worker/src/key.mjs');
export const FIRST_DAY = '2026-10-04';
export const HORIZON_DAYS = 450;
export const MIN_AHEAD_DAYS = 120;
export const AVOID_DAYS = 60;

async function readExisting(file) {
  if (!existsSync(file)) return null;
  const mod = await import(`${pathToFileURL(file).href}?t=${Date.now()}`);
  return mod.default || null;
}

// The schedule extended to `until` (existing days kept as they are).
export function extendSchedule(bank, existing, until) {
  const days = { ...(existing?.days || {}) };
  const keys = Object.keys(days).sort();
  let day = keys.length ? shiftDateKey(keys[keys.length - 1], 1) : FIRST_DAY;
  const recent = keys.slice(-AVOID_DAYS).map(k => days[k]);
  while (day <= until) {
    if (weekdayOf(day) !== 6) {
      const avoid = new Set(recent.flat());
      const ids = pickDailySet(bank.questions, day, { avoid });
      days[day] = ids;
      recent.push(ids);
      if (recent.length > AVOID_DAYS) recent.shift();
    }
    day = shiftDateKey(day, 1);
  }
  const sorted = Object.keys(days).sort();
  return { version: 1, from: sorted[0], to: sorted[sorted.length - 1], days: Object.fromEntries(sorted.map(k => [k, days[k]])) };
}

export function keyFor(bank, schedule) {
  return { version: 1, from: schedule.from, to: schedule.to, days: Object.fromEntries(Object.entries(schedule.days).map(([day, ids]) => [day, ids.map(id => { const q = bank.byId.get(id); return [id, q ? q.answer : -1, q ? q.difficulty : 0]; })])) };
}

const header = what => `// GENERATED by scripts/challenge/build-key.mjs — do not edit by hand. ${what}\n`;
export function scheduleSource(schedule) {
  const lines = Object.entries(schedule.days).map(([day, ids]) => `    '${day}': [${ids.map(id => `'${id}'`).join(', ')}],`);
  return `${header('האתגר העולמי: the five question ids of each day (append-only; no answers here).')}export default {\n  version: ${schedule.version}, from: '${schedule.from}', to: '${schedule.to}',\n  days: {\n${lines.join('\n')}\n  },\n};\n`;
}
export function keySource(key) {
  const lines = Object.entries(key.days).map(([day, rows]) => `    '${day}': [${rows.map(([id, a, d]) => `['${id}', ${a}, ${d}]`).join(', ')}],`);
  return `${header('האתגר העולמי: the answer key of each day — [id, answer index, difficulty]. Server only; never shipped in the app bundle.')}export default {\n  version: ${key.version}, from: '${key.from}', to: '${key.to}',\n  days: {\n${lines.join('\n')}\n  },\n};\n`;
}

export function checkAll(bank, schedule, key, today) {
  const problems = [];
  if (!schedule) return ['the schedule is missing'];
  if (!key) return ['the key is missing'];
  for (const [day, ids] of Object.entries(schedule.days)) {
    if (!isDateKey(day)) problems.push(`${day}: not a date`);
    if (weekdayOf(day) === 6) problems.push(`${day}: a Saturday is scheduled`);
    if (!Array.isArray(ids) || ids.length !== GLOBAL_SIZE) problems.push(`${day}: needs ${GLOBAL_SIZE} ids`);
    if (new Set(ids).size !== ids.length) problems.push(`${day}: a repeated id`);
    for (const id of ids) if (!bank.byId.has(id)) problems.push(`${day}: ${id} is not in the bank`);
  }
  const expected = keyFor(bank, schedule);
  const keyDays = Object.keys(key.days || {}).sort();
  const scheduleDays = Object.keys(schedule.days).sort();
  if (keyDays.join() !== scheduleDays.join()) problems.push('the key and the schedule hold different days');
  for (const day of scheduleDays) {
    const want = JSON.stringify(expected.days[day]);
    const have = JSON.stringify(key.days?.[day]);
    if (want !== have) problems.push(`${day}: the key does not match the bank (${have} ≠ ${want})`);
  }
  const last = scheduleDays[scheduleDays.length - 1];
  if (!last || last < shiftDateKey(today, MIN_AHEAD_DAYS)) problems.push(`the schedule ends ${last || '—'}: extend it (at least ${MIN_AHEAD_DAYS} days ahead of ${today})`);
  return problems;
}

async function main() {
  const args = process.argv.slice(2);
  const check = args.includes('--check');
  const untilArg = args.find(a => a.startsWith('--until='))?.slice(8);
  const today = keyOfUTC(new Date());
  const bank = await loadBank();
  if (bank.errors.length) console.warn(`[build-key] ${bank.errors.length} invalid question(s) in the bank are skipped`);
  const existing = await readExisting(SCHEDULE_FILE);
  if (check) {
    const problems = checkAll(bank, existing, await readExisting(KEY_FILE), today);
    if (problems.length) { console.error(`[build-key --check] ${problems.length} problem(s):\n  ${problems.slice(0, 30).join('\n  ')}`); process.exit(1); }
    console.log(`[build-key --check] ok — ${Object.keys(existing.days).length} days, ${existing.from} … ${existing.to}`);
    return;
  }
  const until = untilArg && isDateKey(untilArg) ? untilArg : shiftDateKey(today, HORIZON_DAYS);
  const schedule = extendSchedule(bank, existing, until);
  const key = keyFor(bank, schedule);
  const problems = checkAll(bank, schedule, key, today);
  if (problems.length) { console.error(problems.join('\n')); process.exit(1); }
  writeFileSync(SCHEDULE_FILE, scheduleSource(schedule));
  writeFileSync(KEY_FILE, keySource(key));
  const added = Object.keys(schedule.days).length - Object.keys(existing?.days || {}).length;
  console.log(`[build-key] ${Object.keys(schedule.days).length} days (${added} new), ${schedule.from} … ${schedule.to}`);
  console.log(`  ${path.relative(ROOT, SCHEDULE_FILE)} · ${readFileSync(SCHEDULE_FILE).length} bytes`);
  console.log(`  ${path.relative(ROOT, KEY_FILE)} · ${readFileSync(KEY_FILE).length} bytes`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) main();
