// Compares, day by day, what the חק לישראל packs contain with the refs of Sefaria's 378 "חק לישראל" sheets — a checking
// aid only: nothing is "fixed" from it. Torah, Nevi'im, Ketuvim (verse by verse), Mishnah (tractate and chapter) and
// Gemara (tractate, daf and amud where it begins). Writes its findings between the validation markers of
// docs/chok-leyisrael.md;  --check fails if that section is not current.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import CHOK from '../../src/data/chokLeYisrael/manifest.mjs';
import { numberOf } from './numbers.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '../..');
const DOC = join(ROOT, 'docs/chok-leyisrael.md');
const START = '<!-- validation:start (generated by scripts/chok-leyisrael/validate.mjs) -->';
const END = '<!-- validation:end -->';
const SHEETS = JSON.parse(readFileSync(join(ROOT, 'sources/torat-emet-chok-leyisrael/sefaria-sheet-refs.json'), 'utf8')).sheets;
const pack = file => JSON.parse(gunzipSync(readFileSync(join(ROOT, 'public/library/packs', CHOK.packId, file))).toString('utf8'));

const BOOKS = { ישעיה: 'Isaiah', ירמיה: 'Jeremiah', ירמיהו: 'Jeremiah', יחזקאל: 'Ezekiel', 'מלכים א': 'I Kings', 'מלכים ב': 'II Kings', 'שמואל א': 'I Samuel', 'שמואל ב': 'II Samuel',
  יהושע: 'Joshua', שופטים: 'Judges', הושע: 'Hosea', עמוס: 'Amos', עובדיה: 'Obadiah', יונה: 'Jonah', מיכה: 'Micah', זכריה: 'Zechariah', מלאכי: 'Malachi', יואל: 'Joel',
  משלי: 'Proverbs', תהילים: 'Psalms' };
const TORAH = { בראשית: 'Genesis', שמות: 'Exodus', ויקרא: 'Leviticus', במדבר: 'Numbers', דברים: 'Deuteronomy' };
const TRACTATES = { ברכות: 'Berakhot', פאה: 'Peah', דמאי: 'Demai', כלאים: 'Kilayim', שביעית: 'Sheviit', תרומות: 'Terumot', שבת: 'Shabbat', עירובין: 'Eruvin', פסחים: 'Pesachim',
  ביצה: 'Beitzah', 'מועד קטן': 'Moed Katan', חגיגה: 'Chagigah', יבמות: 'Yevamot', כתובות: 'Ketubot', נדרים: 'Nedarim', גיטין: 'Gittin', סוטה: 'Sotah', קידושין: 'Kiddushin',
  קדושין: 'Kiddushin', 'בבא קמא': 'Bava Kamma', "ב''ק": 'Bava Kamma', 'בבא מציעא': 'Bava Metzia', מציעא: 'Bava Metzia', 'בבא בתרא': 'Bava Batra', סנהדרין: 'Sanhedrin',
  מכות: 'Makkot', שבועות: 'Shevuot', עדיות: 'Eduyot', 'עבודה זרה': 'Avodah Zarah', "ע''ז": 'Avodah Zarah', זבחים: 'Zevachim', מנחות: 'Menachot', חולין: 'Chullin',
  בכורות: 'Bekhorot', ערכין: 'Arakhin', אהלות: 'Oholot', נגעים: 'Negaim', פרה: 'Parah', 'מסכת פרה': 'Parah', מקואות: 'Mikvaot', נדה: 'Niddah', ידים: 'Yadayim', 'מסכת ידים': 'Yadayim' };

// Verse counts of every chapter, from the app's own Tanakh (uxlc-2.5).
const counts = new Map();
const chaptersOf = book => {
  if (!counts.has(book)) {
    const file = join(ROOT, 'public/library/packs/uxlc-2.5', `${book.replace(/ /g, '_')}.json.gz`);
    counts.set(book, existsSync(file) ? JSON.parse(gunzipSync(readFileSync(file))).nodes.map(node => node.units.length) : []);
  }
  return counts.get(book);
};
function expand(ref) {
  const m = /^(.+?) (\d+)(?::(\d+))?(?:-(\d+)(?::(\d+))?)?$/.exec(ref);
  if (!m) return [];
  const [, book, c1s, v1s, a, b] = m;
  const c1 = Number(c1s);
  const v1 = v1s ? Number(v1s) : 1;
  let c2 = c1;
  let v2;
  if (a && b) { c2 = Number(a); v2 = Number(b); } else if (a) { if (v1s) v2 = Number(a); else { c2 = Number(a); v2 = chaptersOf(book)[c2 - 1]; } } else v2 = v1s ? v1 : chaptersOf(book)[c1 - 1];
  const out = [];
  for (let c = c1; c <= c2; c += 1) {
    const last = c === c2 ? v2 : chaptersOf(book)[c - 1];
    for (let v = c === c1 ? v1 : 1; v <= last; v += 1) out.push(`${book} ${c}:${v}`);
  }
  return out;
}

const sheetFor = new Map(SHEETS.map(sheet => {
  const m = /פרשת (.+) (יום ראשון|יום שני|יום שלישי|יום רביעי|יום חמישי|ליל שישי|יום שישי)$/.exec(sheet.title);
  return [m ? `${m[1].replace(/[^א-ת ]/g, '')}|${m[2]}` : sheet.title, sheet];
}));
const DAY_HE = { sun: 'יום ראשון', mon: 'יום שני', tue: 'יום שלישי', wed: 'יום רביעי', thu: 'יום חמישי', 'fri-night': 'ליל שישי', fri: 'יום שישי' };
const SHEET_NAMES = { 'chayei-sara': 'חיי שרה', korach: 'קורח', bechukotai: 'בחוקותי', shlach: 'שלח לך', 'ki-tisa': 'כי תשא', tetzaveh: 'תצוה', 'lech-lecha': 'לך לך', pinchas: 'פנחס' };
const sheetRefs = (sheet, heading) => sheet?.sections.filter(section => section.h === heading).flatMap(section => section.refs) || [];
const compactRange = list => {
  if (!list.length) return '—';
  return list.length === 1 ? list[0] : `${list[0]} … ${list[list.length - 1].replace(/^.* /, '')} (${list.length})`;
};

export function validate() {
  const rows = [];
  const totals = { days: 0, sheets: 0, torah: [0, 0], neviim: [0, 0], ketuvim: [0, 0], mishnah: [0, 0], gemara: [0, 0], friNightSubset: 0 };
  const missingSheets = [];
  for (const meta of CHOK.parashot) {
    const data = pack(meta.file);
    const bookEn = TORAH[meta.book];
    let chapter = null;
    for (const day of data.days) {
      totals.days += 1;
      const names = [SHEET_NAMES[meta.id], meta.he, data.edition].filter(Boolean);
      const sheet = names.map(name => sheetFor.get(`${name.replace(/[^א-ת ]/g, '')}|${DAY_HE[day.key]}`)).find(Boolean);
      if (!sheet) { missingSheets.push(`${meta.he} · ${DAY_HE[day.key]}`); }
      else totals.sheets += 1;
      const label = `${meta.he} · ${DAY_HE[day.key]}`;
      for (const part of day.parts) {
        if (part.key === 'torah') {
          const mine = [];
          if (chapter === null) chapter = Number(/ (\d+):/.exec(CHOK_REF[meta.id])[1]);
          for (const section of part.s) for (const block of section.b) if (block.t === 'v') { if (block.c) chapter = numberOf(block.c); mine.push(`${bookEn} ${chapter}:${numberOf(block.n)}`); }
          if (!sheet) continue;
          const theirs = sheetRefs(sheet, 'תורה').flatMap(expand);
          const extra = mine.filter(ref => !theirs.includes(ref));
          const absent = theirs.filter(ref => !mine.includes(ref));
          totals.torah[0] += 1;
          // ליל שישי: the edition takes 26 chosen verses inside the range the sheet names (it lists the whole range).
          if (day.key === 'fri-night' && !extra.length && mine[0] === theirs[0]) { totals.friNightSubset += 1; continue; }
          if (extra.length || absent.length) { totals.torah[1] += 1; rows.push({ label, part: 'תורה', edition: compactRange(mine), sheet: sheetRefs(sheet, 'תורה').join('; '), note: [extra.length ? `במהדורה ולא בדף: ${extra.slice(0, 6).join(', ')}${extra.length > 6 ? ` ועוד ${extra.length - 6}` : ''}` : '', absent.length ? `בדף ולא במהדורה: ${absent.slice(0, 6).join(', ')}${absent.length > 6 ? ` ועוד ${absent.length - 6}` : ''}` : ''].filter(Boolean).join(' · ') }); }
        }
        if ((part.key === 'neviim' || part.key === 'ketuvim') && sheet) {
          const heading = part.s[0].h || '';
          const [, bookHe, chapterHe] = heading.split(/\s+-\s+/);
          const book = BOOKS[bookHe];
          let c = numberOf((chapterHe || '').replace('פרק', ''));
          const mine = [];
          for (const section of part.s) for (const block of section.b) if (block.t === 'v') { if (block.c) c = numberOf(block.c); mine.push(`${book} ${c}:${numberOf(block.n)}`); }
          const theirs = sheetRefs(sheet, CHOK_PART_HE[part.key]).flatMap(expand);
          totals[part.key][0] += 1;
          const extra = mine.filter(ref => !theirs.includes(ref));
          const absent = theirs.filter(ref => !mine.includes(ref));
          if (extra.length || absent.length) { totals[part.key][1] += 1; rows.push({ label, part: CHOK_PART_HE[part.key], edition: `${heading} · ${compactRange(mine)}`, sheet: sheetRefs(sheet, CHOK_PART_HE[part.key]).join('; '), note: [extra.length ? `במהדורה ולא בדף: ${extra.slice(0, 6).join(', ')}` : '', absent.length ? `בדף ולא במהדורה: ${absent.slice(0, 6).join(', ')}${absent.length > 6 ? ` ועוד ${absent.length - 6}` : ''}` : ''].filter(Boolean).join(' · ') }); }
        }
        if (part.key === 'mishnah' && sheet) {
          const heading = part.s[0].h || '';
          const m = /^משנה\s+(.+?)\s+פרק\s+(\S+)/.exec(heading);
          const mine = m ? `Mishnah ${TRACTATES[m[1]] || m[1]} ${numberOf(m[2])}` : heading;
          const theirs = sheetRefs(sheet, 'משנה');
          totals.mishnah[0] += 1;
          if (!theirs.some(ref => ref === mine || ref.startsWith(`${mine}:`))) { totals.mishnah[1] += 1; rows.push({ label, part: 'משנה', edition: `${heading} (${mine})`, sheet: theirs.join('; ') || '—', note: '' }); }
        }
        if (part.key === 'gemara' && sheet) {
          const heading = part.s[0].h || '';
          const m = /^גמרא\s+(.+?)\s+דף\s+(\S+)\s+ע(?:''|״|")([אב])/.exec(heading);
          const mine = m ? `${TRACTATES[m[1]] || m[1]} ${numberOf(m[2])}${m[3] === 'א' ? 'a' : 'b'}` : heading;
          const theirs = sheetRefs(sheet, 'גמרא');
          totals.gemara[0] += 1;
          if (!theirs.some(ref => ref.startsWith(`${mine}:`) || ref === mine || ref.startsWith(`${mine}-`))) { totals.gemara[1] += 1; rows.push({ label, part: 'גמרא', edition: `${heading} (${mine})`, sheet: theirs.join('; ') || '—', note: '' }); }
        }
      }
    }
  }
  return { rows, totals, missingSheets };
}
const CHOK_PART_HE = { neviim: 'נביאים', ketuvim: 'כתובים' };
const CHOK_REF = Object.fromEntries((await import('../../src/data/shnayimMikraRanges.mjs')).SHNAYIM_MIKRA_CANONICAL_RANGES.map(item => [item.id, item.reference]));

function render({ rows, totals, missingSheets }) {
  const pct = ([all, bad]) => `${all - bad} מתוך ${all} תואמים${bad ? ` · ${bad} שונים` : ''}`;
  const lines = [START, '',
    `נבדקו ${totals.days} ימים; לכל אחד נמצא דף בספריא: ${totals.sheets}${missingSheets.length ? ` (חסרים: ${missingSheets.join(', ')})` : ''}.`, '',
    '| חלק | תוצאה |', '|---|---|',
    `| תורה | ${pct(totals.torah)}; בליל שישי ${totals.friNightSubset} ימים: 26 הפסוקים שבמהדורה נמצאים בתוך הטווח שהדף מציין (הדף מונה את כל הטווח) |`,
    `| נביאים | ${pct(totals.neviim)} |`, `| כתובים | ${pct(totals.ketuvim)} |`, `| משנה (מסכת ופרק) | ${pct(totals.mishnah)} |`, `| גמרא (מסכת, דף ועמוד שבו מתחיל הקטע) | ${pct(totals.gemara)} |`, '',
  ];
  if (rows.length) {
    lines.push('ההבדלים, יום אחר יום (הטקסט שבאפליקציה הוא של המהדורה, כפי שהוא; הדפים בספריא הם כלי בדיקה בלבד):', '', '| יום | חלק | המהדורה | הדף בספריא | פירוט |', '|---|---|---|---|---|');
    for (const row of rows) lines.push(`| ${row.label} | ${row.part} | ${row.edition.replace(/\|/g, '/')} | ${row.sheet.replace(/\|/g, '/')} | ${row.note.replace(/\|/g, '/')} |`);
  } else lines.push('לא נמצאו הבדלים.');
  lines.push('', END);
  return lines.join('\n');
}

const section = render(validate());
const doc = existsSync(DOC) ? readFileSync(DOC, 'utf8') : '';
const next = doc.includes(START) ? doc.replace(new RegExp(`${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END}`), section) : `${doc}\n${section}\n`;
if (process.argv.includes('--check')) {
  if (next !== doc) { console.error('docs/chok-leyisrael.md: the validation section is stale (run scripts/chok-leyisrael/validate.mjs)'); process.exit(1); }
  console.log('validation section current');
} else {
  writeFileSync(DOC, next);
  console.log(section.split('\n').slice(2, 12).join('\n'));
}
