// שלום רב — stage 3: the segmented book (sources/shalom-rav/extracted/book.json) becomes the app's data module
// src/data/shalomRav/book.mjs, with every entry's provenance and verification status, and the content inventory
// docs/shalom-rav/content-inventory.md.
//
// Only typography is normalized here (the brief allows it): gershayim and geresh typed as ” and ’ become ״ and ׳
// (החיד״א, ה׳); a quotation opened with ‘ keeps its ’. Words, points and order are the book's.
// Usage: node scripts/shalom-rav/build.mjs
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';

const book = JSON.parse(readFileSync('sources/shalom-rav/extracted/book.json', 'utf8'));
const reviewDir = 'sources/shalom-rav/review';
const pageReview = new Map();
for (const name of readdirSync(reviewDir).filter(name => /^review-.*\.json$/.test(name)).sort()) {
  for (const page of JSON.parse(readFileSync(`${reviewDir}/${name}`, 'utf8')).pages) pageReview.set(page.page, { ...page, file: name });
}

const HEB = 'א-ת';
export function typography(text) {
  let out = String(text)
    .replace(new RegExp(`([${HEB}][\\u0591-\\u05C7]*)(”|“|’’|‘‘)(?=[${HEB}])`, 'g'), '$1״')   // gershayim inside a word
    .replace(/\s+([,.:;])/g, '$1').replace(/\(\s+/g, '(').replace(/\s+\)/g, ')');
  // geresh: a ’ right after a word, unless it closes a quotation opened with ‘
  let open = false;
  out = [...out].map((ch, i, all) => {
    if (ch === '‘') { open = true; return ch; }
    if (ch === '’') {
      if (open) { open = false; return ch; }
      return new RegExp(`[${HEB}\\u0591-\\u05C7]`).test(all[i - 1] || '') ? '׳' : ch;
    }
    return ch;
  }).join('');
  return out;
}

const statusOf = entry => {
  const [a, b] = entry.printedPages;
  const pages = [];
  for (let p = a; p <= b; p++) pages.push(p);
  const reviews = pages.map(p => pageReview.get(p));
  if (reviews.some(r => !r)) return { status: 'NORMALIZED', reviewedPages: reviews.filter(Boolean).length, pages: pages.length, reasons: [] };
  const open = reviews.filter(r => r.status !== 'VISUALLY_VERIFIED');
  return {
    status: open.length ? 'REVIEW_REQUIRED' : 'VISUALLY_VERIFIED',
    reviewedPages: pages.length, pages: pages.length,
    corrections: reviews.reduce((n, r) => n + (r.corrections?.length || 0), 0),
    reasons: open.map(r => `עמ׳ ${r.page}: ${r.notes || 'לבדיקה'}`),
    bookNotes: reviews.reduce((n, r) => n + (r.bookNotes?.length || 0), 0),  // the notes themselves stay in sources/shalom-rav/review/
  };
};

const entries = book.entries.map(entry => {
  const verification = statusOf(entry);
  const blocks = entry.blocks.map(block => ({
    ...block,
    ...(block.text ? { text: typography(block.text) } : {}),
    ...(block.title ? { title: typography(block.title) } : {}),
  }));
  return {
    ...entry,
    title: typography(entry.title),
    ...(entry.personalization ? { personalization: { ...entry.personalization, placeholders: entry.personalization.placeholders.map(item => ({ ...item, token: typography(item.token) })) } } : {}),
    ...(entry.subtitle ? { subtitle: typography(entry.subtitle) } : {}),
    book: 'shalom-rav',
    source: { book: 'שלום רב — תפילות וברכות / תפילות וסגולות', pdf: 'sources/shalom-rav/Sidur_16X11.pdf', printedPages: entry.printedPages, pdfPages: entry.pdfPages },
    hasExplanation: blocks.some(block => block.type === 'explanation'),
    hasInstruction: blocks.some(block => block.type === 'instruction') || blocks.some(block => /\([^)]*\)/.test(block.text || '')),
    extraction: 'EXTRACTED+NORMALIZED',
    verification,
    blocks,
  };
});

const data = {
  book: Object.fromEntries(Object.entries(book.book).map(([key, value]) => [key, typography(value)])),
  categories: book.categories,
  needs: book.needs,
  toc: book.toc.map(item => ({ ...item, title: typography(item.title) })),
  entries,
};
mkdirSync('src/data/shalomRav', { recursive: true });
writeFileSync('src/data/shalomRav/book.mjs', `// שלום רב — generated by scripts/shalom-rav/build.mjs from the supplied PDF (sources/shalom-rav/Sidur_16X11.pdf);
// do not edit by hand: fix the extraction (sources/shalom-rav/corrections.json, the review files) and rebuild.
// Explanations and introductions: הרב שלום יוסף ברבי. Traditional and attributed texts keep the book's attribution.
export default ${JSON.stringify(data, null, 1)};
`);

// The content inventory.
const typeName = { prayer: 'תפילה', blessing: 'ברכה', segulah: 'סגולה', strengthening: 'חיזוק', explanation: 'הסבר', ritual_order: 'סדר', source_text: 'מקור', psalms_scripture: 'מקרא', personal_prayer: 'תפילה אישית', attributed_prayer: 'תפילה מיוחסת' };
const cat = Object.fromEntries(book.categories.map(c => [c.key, c.title]));
const originName = { author: 'המחבר', attributed: 'מיוחס', scripture: 'מקרא', traditional: 'מסורתי', unstated: 'לא צוין' };
const rows = entries.map(e => `| ${e.order} | ${e.title} | ${e.pdfPages.join('–')} | ${e.printedPages.join('–')} | ${typeName[e.contentType] || e.contentType} | ${cat[e.category] || 'על הספר'} | ${e.hasExplanation ? 'כן' : '—'} | ${e.hasInstruction ? 'כן' : '—'} | ${e.blocks.some(b => b.type === 'text' || b.type === 'source') ? 'כן' : '—'} | ${e.personalization ? 'כן' : '—'} | ${originName[e.origin]}${e.attributedTo ? `: ${e.attributedTo}` : ''} | ${e.verification.status}${e.verification.corrections ? ` (${e.verification.corrections} תיקונים)` : ''} |`);
mkdirSync('docs/shalom-rav', { recursive: true });
writeFileSync('docs/shalom-rav/content-inventory.md', `# שלום רב — content inventory

Generated by \`scripts/shalom-rav/build.mjs\`. Source: \`sources/shalom-rav/Sidur_16X11.pdf\` (57 PDF pages: a table of
contents, a title page and 54 two-page spreads — printed pages 1–110). ${entries.length} entries in the book's order.

Pipeline: \`extract.py\` (glyphs → lines, points attached by glyph and position) → \`segment.py\` (corrections, paragraphs,
entries, block roles by the book's fonts and \`spec.json\`) → \`build.mjs\` (typography, provenance, verification).
Checks: \`validate.py\` (impossible pointing), \`tanakh-check.py\` (the quoted Tanakh against the Leningrad Codex),
\`dagesh-check.mjs\` (dagesh and dots against every pointed word in the app), then a visual review of every page
(\`sources/shalom-rav/review/\`).

| # | כותרת | עמ׳ PDF | עמ׳ בספר | סוג | קטגוריה | הסבר | הוראות | נוסח | שמות להשלמה | ייחוס | אימות |
|---|---|---|---|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`);
const count = s => entries.filter(e => e.verification.status === s).length;
console.log(`entries ${entries.length} | verified ${count('VISUALLY_VERIFIED')} | review required ${count('REVIEW_REQUIRED')} | not yet reviewed ${count('NORMALIZED')} | ${Math.round(readFileSync('src/data/shalomRav/book.mjs').length / 1024)} KB`);
