// Exact links from the notes of עונג שבת ("מקורות וטעמים") to texts the app already carries. Only EXACT links are made:
// a citation that names siman and se'if (שולחן ערוך אורח חיים), perek and halacha (רמב״ם הלכות שבת), or tractate, daf
// and amud (תלמוד בבלי), and whose target exists in the bundled edition. Anything else stays text (see
// docs/halacha/ong-shabbat-audit.md §G for the classification of every cited work).
// Run: node scripts/halacha/ong-shabbat/links.mjs --book <book.json>   → src/data/ongShabbatLinks.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { workById } from '../../../src/data/library/registry.mjs';
import talmudCatalog from '../../../src/data/talmudCatalog.mjs';
import { hebrewNumeral } from '../../../src/services/hebrewNumerals.mjs';

const ROOT = fileURLToPath(new URL('../../..', import.meta.url));
const args = process.argv.slice(2);
const book = JSON.parse(readFileSync(args[args.indexOf('--book') + 1], 'utf8'));

const VALUE = { א: 1, ב: 2, ג: 3, ד: 4, ה: 5, ו: 6, ז: 7, ח: 8, ט: 9, י: 10, כ: 20, ך: 20, ל: 30, מ: 40, ם: 40, נ: 50, ן: 50, ס: 60, ע: 70, פ: 80, ף: 80, צ: 90, ץ: 90, ק: 100, ר: 200, ש: 300, ת: 400 };
export const hebrewValue = token => [...String(token).replace(/["'״׳]/g, '')].reduce((sum, letter) => sum + (VALUE[letter] || NaN), 0);
const N = '([א-ת]{1,3}(?:["״][א-ת])?[\'׳]?)';

const sa = workById('Shulchan_Arukh__Orach_Chayim');
const rambam = workById('Mishneh_Torah__Sabbath');
const TRACTATES = { שבת: 'Shabbat', יומא: 'Yoma', פסחים: 'Pesachim', ברכות: 'Berakhot', ביצה: 'Beitzah', עירובין: 'Eruvin' };
const amudCount = title => talmudCatalog.tractates.find(item => item.title === title)?.amudCount || 0;

// A citation only counts when the note is about Orach Chayim: chapters ב׳–כ״ה (Shabbat, blessings) and the Shabbat
// halachot of chapter א׳. Chapter א׳ ב׳–ז׳ (ovens and pots, meat, milk and fish) belong to Yoreh De'ah, so there a siman is
// linked only when the note itself says "אורח חיים".
const YOREH_DEAH = new Set(['1.2', '1.3', '1.4', '1.5', '1.6', '1.7']);
function linksOf(note, chapter, unit) {
  const links = [];
  const text = note.text;
  for (const m of text.matchAll(new RegExp(`שולחן ערוך,?\\s*\\[?\\s*(אורח חיים\\s*)?סימן ${N}\\s*סעי(?:ף|פים) ${N}`, 'g'))) {
    if (YOREH_DEAH.has(`${chapter}.${unit}`) && !m[1]) continue;
    const siman = hebrewValue(m[2]); const seif = hebrewValue(m[3]);
    if (!(siman >= 1 && siman <= sa.editions[0].expected.length && seif >= 1 && seif <= sa.editions[0].expected[siman - 1])) continue;
    links.push({ kind: 'shulchan-arukh', label: `שולחן ערוך, אורח חיים ${hebrewNumeral(siman)}, ${hebrewNumeral(seif)}`, workId: sa.workId, node: siman, unit: seif, cited: m[0] });
  }
  for (const m of text.matchAll(new RegExp(`רמב"ם\\s*\\[?\\s*(?:הלכות שבת פרק ${N} הלכה ${N}|פרק ${N} מהלכות שבת הלכה ${N})`, 'g'))) {
    const perek = hebrewValue(m[1] || m[3]); const halacha = hebrewValue(m[2] || m[4]);
    if (!(perek >= 1 && perek <= rambam.editions[0].expected.length && halacha >= 1 && halacha <= rambam.editions[0].expected[perek - 1])) continue;
    links.push({ kind: 'rambam', label: `רמב״ם, הלכות שבת ${hebrewNumeral(perek)}, ${hebrewNumeral(halacha)}`, workId: rambam.workId, node: perek, unit: halacha, cited: m[0] });
  }
  for (const m of text.matchAll(new RegExp(`(?:גמרא|מסכת)\\s*\\[?\\s*(?:מסכת\\s*)?(${Object.keys(TRACTATES).join('|')})\\s*(?:דף\\s*)?${N}\\s*(?:עמוד|ע")\\s*([אב])`, 'g'))) {
    const title = TRACTATES[m[1]]; const daf = hebrewValue(m[2]); const amud = m[3] === 'א' ? 'a' : 'b';
    const index = (daf - 2) * 2 + (amud === 'b' ? 1 : 0);
    if (!(daf >= 2 && index < amudCount(title))) continue;
    links.push({ kind: 'talmud', label: `תלמוד בבלי, ${m[1]} ${hebrewNumeral(daf)}${amud === 'a' ? '.' : ':'}`, route: `talmud/${title}/${daf}${amud}`, cited: m[0] });
  }
  return links;
}

const noteChapter = new Map();
const noteUnit = new Map();
for (const chapter of book.chapters) for (const unit of chapter.units) for (const ref of unit.refs) { noteChapter.set(ref.n, chapter.n); noteUnit.set(ref.n, unit.n); }
const out = {};
let total = 0;
for (const note of book.footnotes) {
  const links = linksOf(note, noteChapter.get(note.n), noteUnit.get(note.n));
  if (links.length) { out[note.n] = links; total += links.length; }
}
writeFileSync(join(ROOT, 'src/data/ongShabbatLinks.mjs'), `// Generated by scripts/halacha/ong-shabbat/links.mjs. Do not edit by hand.\n// Exact links from the notes of עונג שבת (by note number) to the bundled Shulchan Arukh, Rambam and Talmud; each target verified to exist.\nexport const ONG_SHABBAT_NOTE_LINKS = ${JSON.stringify(out)};\n`);
console.log(JSON.stringify({ notesWithLinks: Object.keys(out).length, links: total, byKind: Object.values(out).flat().reduce((map, link) => ({ ...map, [link.kind]: (map[link.kind] || 0) + 1 }), {}) }));
