// Reviewed structural map for Siddur Edot HaMizrach (Sefaria, Shaliehsaboo Edition, CC0),
// Weekday Mincha. Import-time artifact: scripts/build-weekday-mincha-pack.mjs turns it into
// fixed offsets + checksums. Runtime never infers roles from wording.
//
// A segment is either unlisted (plain recited text, must contain no <small>/<big>),
// a string (one block for the whole segment), or an array (one role per markup piece,
// in order; piece boundaries are <small>, <big> and <br> tags).
//
// Roles: heading | recited | instruction | source | label   (optionally "@condition")
//   label    = a selection caption such as "בקיץ:" — shown only in the unadapted full-source view,
//              because in an adapted prayer the selection itself is already made.
// Conditions are resolved in src/services/prayer/weekdayMinchaRules.mjs.

export const SECTIONS = [
  { id: 'offerings', key: 'Offerings' },
  { id: 'amida', key: 'Amida' },
  { id: 'vidui', key: 'Vidui' },
  { id: 'alenu', key: 'Alenu' },
];

const repeat = (from, to, spec) => Object.fromEntries(Array.from({ length: to - from + 1 }, (_, i) => [from + i, spec]));

export const MAP = {
  offerings: {
    0: 'heading',
    1: 'recited',
    7: 'recited',
    14: 'instruction@minyan',
    15: 'recited@minyan',
  },
  amida: {
    0: 'heading',
    2: ['recited', 'instruction@aseret', 'recited@aseret', 'recited'],
    4: ['label@gevurot-summer', 'recited@gevurot-summer', 'label@gevurot-winter', 'recited@gevurot-winter'],
    5: ['recited', 'instruction@aseret', 'recited@aseret', 'recited'],
    6: ['heading@minyan', 'instruction@minyan'],
    7: 'recited@minyan',
    8: ['recited', 'instruction@aseret', 'recited@aseret'],
    13: 'instruction@fast-chazara',
    14: 'recited@fast-chazara',
    15: 'recited@fast-chazara',
    17: 'label@hashanim-summer',
    18: 'recited@hashanim-summer',
    19: 'label@hashanim-winter',
    20: 'recited@hashanim-winter',
    22: ['recited', 'instruction@aseret', 'recited@aseret'],
    26: 'recited@tisha-beav',
    27: ['recited@tisha-beav', 'instruction@tisha-beav'],
    31: ['instruction@fast', 'recited@fast'],
    32: ['instruction@fast', 'recited@fast'],
    35: 'instruction@yaaleh',
    36: 'recited@yaaleh',
    37: ['label@yaaleh-rosh-chodesh', 'recited@yaaleh-rosh-chodesh'],
    38: ['label@yaaleh-pesach', 'recited@yaaleh-pesach'],
    39: ['label@yaaleh-sukkot', 'recited@yaaleh-sukkot'],
    40: 'recited@yaaleh',
    42: ['instruction', 'source'],
    44: ['heading@minyan', 'instruction@minyan', 'recited@minyan'],
    45: 'instruction@al-hanissim',
    46: 'recited@al-hanissim',
    47: ['label@chanukah', 'recited@chanukah'],
    48: ['label@purim', 'recited@purim'],
    49: ['recited', 'instruction@aseret', 'recited@aseret', 'recited'],
    50: 'heading@birkat-kohanim',
    51: 'instruction@birkat-kohanim',
    52: ['instruction@birkat-kohanim', 'recited@birkat-kohanim'],
    53: ['instruction@birkat-kohanim', 'recited@birkat-kohanim'],
    54: ['instruction@birkat-kohanim', 'recited@birkat-kohanim'],
    55: 'instruction@birkat-kohanim',
    56: 'recited@birkat-kohanim',
    57: ['instruction@birkat-kohanim', 'recited@birkat-kohanim'],
    58: 'instruction@birkat-kohanim',
    59: 'recited@birkat-kohanim',
    60: 'recited@birkat-kohanim',
    61: 'recited@birkat-kohanim',
    62: 'recited@birkat-kohanim',
    63: ['recited', 'instruction@aseret', 'recited@aseret', 'recited'],
    65: 'recited',
    66: ['instruction', 'recited'],
    67: ['recited', 'instruction', 'recited'],
    68: ['instruction', 'recited'],
    69: ['instruction@fast', 'recited@fast'],
    70: ['recited', 'instruction@aseret', 'recited'],
    71: 'recited',
    72: 'instruction@aseret',
    ...repeat(73, 104, 'recited@aseret'),
    105: 'instruction@yehi-shem',
    106: ['recited@yehi-shem', 'instruction@yehi-shem'],
  },
  vidui: {
    0: 'heading@tachanun',
    ...repeat(1, 4, 'recited@tachanun'),
    5: 'instruction@tachanun',
    6: ['recited@tachanun', 'source@tachanun', 'recited@tachanun', 'recited@tachanun'],
    7: 'recited@tachanun',
    8: 'recited@tachanun',
    9: 'recited@tachanun',
    10: 'instruction@minyan',
    11: 'recited@minyan',
    12: 'recited@minyan',
    13: 'recited@minyan',
    14: ['instruction@minyan', 'recited@minyan'],
    15: 'label',
    16: 'recited@not-friday',
    17: 'label',
    18: ['source@friday', 'recited@friday'],
    19: 'instruction@fast',
    20: ['source@fast', 'recited@fast'],
    21: 'instruction@minyan',
    22: 'recited@minyan',
    23: 'recited@minyan',
  },
  alenu: {
    0: 'heading',
    3: 'recited',
  },
};
