// The content-completeness matrix of the four rites, read from the bundled packs and layouts — never typed by hand.
// COMPLETE: the rite's edition has the section and it is bundled; PARTIAL: present but unpointed or only part of it;
// MISSING: the rite's licensed source has no such section (Chabad Shabbat / festivals); SOURCE-BLOCKED: exists at the
// source but could not be bundled for licence reasons. Writes docs/siddur/nusach-completeness.md.
import { writeFileSync, mkdirSync } from 'node:fs';
import { NUSACHIM } from '../src/data/nusach/registry.mjs';
import { SIDDUR_SOURCES } from '../src/data/nusach/manifest.mjs';
import { siddurLayout } from '../src/data/nusach/siddurLayouts.mjs';
import { loadSiddur } from '../src/services/nusach.mjs';
import { siddurRoots } from '../src/services/siddurIndex.mjs';

const NIKUD = /[ְ-ּ]/;
const ROWS = [
  ['Weekday Shacharit', { prayer: 'shacharit' }],
  ['Weekday Mincha', { prayer: 'mincha' }],
  ['Weekday Maariv', { prayer: 'maariv' }],
  ['Shema and blessings', { prayer: 'shacharit', concept: 'shema' }],
  ['Weekday Amidah', { prayer: 'shacharit', concept: 'amida' }],
  ['Tachanun / Vidui', { prayer: 'shacharit', text: /נפילת אפים|נפילת אפיים|והוא רחום יכפר|אשמנו בגדנו/ }],
  ['Kaddish (in the services)', { text: /יתגדל ויתקדש/ }],
  ['Friday night (Kabbalat Shabbat / Maariv)', { shabbat: 'maariv', anyRoot: /kabbalat shabbat/i }],
  ['Kiddush', { any: /kiddush/i, text: /מקדש השבת/ }],
  ['Shabbat Shacharit', { shabbat: 'shacharit' }],
  ['Shabbat Musaf', { anyRoot: /musaf|mussaf/i, text: /תכנת שבת|למשה צוית/ }],
  ['Shabbat Mincha', { shabbat: 'mincha' }],
  ['Havdalah', { any: /havdal/i, text: /המבדיל בין קדש לחול/ }],
  ['Birkat Hamazon', { concept: 'birkat-hamazon' }],
  ['Rosh Chodesh (Musaf / Hallel)', { anyRoot: /rosh (chodesh|hodesh)/i }],
  ['Hallel', { concept: 'hallel' }],
  ['Festivals (Amidah / Musaf)', { anyRoot: /festival|regalim|holidays/i }],
  ['Omer', { concept: 'omer' }],
  ['Tallit / Tefillin', { text: /להתעטף בציצית|להניח תפילין/ }],
  ['Bedtime Shema', { any: /bedtime|al hamita|retiring/i }],
  ['Selichot (fast days)', { anyRoot: /selichot|fast days/i }],
];

const lines = ['# Siddur completeness by rite', '', `Generated by scripts/nusach-matrix.mjs on ${new Date().toISOString().slice(0, 10)} from the bundled packs.`, '', '| Section | ' + NUSACHIM.map(item => item.title).join(' | ') + ' |', '|---|' + NUSACHIM.map(() => '---').join('|') + '|'];
const packs = Object.fromEntries(await Promise.all(NUSACHIM.map(async item => [item.id, await loadSiddur(item.id)])));
const rootsOf = Object.fromEntries(NUSACHIM.map(item => [item.id, siddurRoots(packs[item.id].schema.nodes, item.index, siddurLayout(item.id), () => true, { has: ref => Boolean(packs[item.id].texts[ref]) })]));

function verdict(id, spec) {
  const pack = packs[id];
  const roots = rootsOf[id];
  const layout = siddurLayout(id);
  const textOf = item => item.reference.split('; ').map(ref => pack.texts[ref]?.he.join(' ') || '').join(' ');
  let items = [];
  if (spec.prayer) { const key = layout.prayerRoots.weekday[spec.prayer]; items = roots.filter(root => root.key === key).flatMap(root => root.items); }
  if (spec.shabbat) { const key = layout.prayerRoots.shabbat?.[spec.shabbat]; if (!key) return 'MISSING'; items = roots.filter(root => root.key === key).flatMap(root => root.items); }
  if (spec.anyRoot) items = roots.filter(root => spec.anyRoot.test(root.key)).flatMap(root => root.items);
  if (spec.any) items = roots.flatMap(root => root.items).filter(item => spec.any.test(`${item.en} ${item.rootEn}`));
  if (spec.concept) items = (items.length ? items : roots.flatMap(root => root.items)).filter(item => item.concept === spec.concept);
  if (spec.title) items = items.filter(item => spec.title.test(item.en));
  if (spec.text) items = (items.length || spec.prayer || spec.anyRoot || spec.any || spec.concept ? items : roots.flatMap(root => root.items)).filter(item => spec.text.test(textOf(item).replace(/[\u0591-\u05C7]/g, '')));
  if (!items.length) return 'MISSING';
  // Unpointed: recited text (outside the edition's small-print instructions) longer than 200 letters with no nikud.
  const recited = item => textOf(item).replace(/<small>[\s\S]*?<\/small>/g, '').replace(/<[^>]+>/g, '');
  const unpointed = items.filter(item => !NIKUD.test(recited(item)) && recited(item).length > 200);
  return unpointed.length ? 'PARTIAL (unpointed in source)' : 'COMPLETE';
}
for (const [label, spec] of ROWS) lines.push(`| ${label} | ${NUSACHIM.map(item => verdict(item.id, spec)).join(' | ')} |`);
lines.push('', '## Sources', '');
for (const item of NUSACHIM) { const source = SIDDUR_SOURCES[item.id]; lines.push(`- **${item.title}** — ${source.work}; ${source.version}; ${source.provider}; licence ${source.license}; ${Object.keys(packs[item.id].texts).length} bundled texts; excluded: ${(packs[item.id].source.excludedLeaves || []).length ? packs[item.id].source.excludedLeaves.map(leaf => `${leaf.ref} (${leaf.why})`).join('; ') : 'none'}.`); }
mkdirSync(new URL('../docs/siddur/', import.meta.url), { recursive: true });
writeFileSync(new URL('../docs/siddur/nusach-completeness.md', import.meta.url), lines.join('\n') + '\n');
console.log(lines.join('\n'));
