// Siddur QA reports, from the bundled packs and the compositions — never typed by hand:
//   docs/siddur/siddur-qa.md       completeness by rite and service (VERIFIED COMPLETE / … / UNVERIFIED) with every problem
//   docs/siddur/content-table.csv  every section: rite, service, concept, source address, paragraphs, order, required, verified
//   docs/siddur/text-audit.md      suspicious text in each pack, with the exact address and words
// Usage: node scripts/siddur-qa.mjs [nusach] [--quiet]
import { writeFileSync, mkdirSync } from 'node:fs';
import { NUSACHIM } from '../src/data/nusach/registry.mjs';
import { loadSiddur } from '../src/services/nusach.mjs';
import { COMPOSITIONS } from '../src/data/nusach/compositions/index.mjs';
import { SERVICES, COMPLETENESS } from '../src/data/nusach/prayerSchema.mjs';
import { checkRite, auditText } from '../src/services/prayer/siddurQa.mjs';

const only = process.argv.slice(2).find(arg => !arg.startsWith('--'));
const quiet = process.argv.includes('--quiet');
const rites = NUSACHIM.filter(item => !only || item.id === only);
const results = {};
const audits = {};
for (const rite of rites) {
  const pack = await loadSiddur(rite.id);
  results[rite.id] = checkRite(COMPOSITIONS[rite.id], pack.texts);
  audits[rite.id] = auditText(pack);
}

const md = ['# Siddur QA — completeness by rite', '', `Generated by scripts/siddur-qa.mjs on ${new Date().toISOString().slice(0, 10)}. Levels: ${Object.values(COMPLETENESS).join(' · ')}.`, '',
  'VERIFIED COMPLETE = every required concept present in the right order, every anchor found, every paragraph of every leaf used either shown or omitted with a stated reason, no paragraph used twice, every conditional caption known to the day engine, and the mapping read through (reviewed).', '',
  `| Service | ${rites.map(rite => rite.title).join(' | ')} |`, `|---|${rites.map(() => '---').join('|')}|`];
for (const schema of SERVICES) md.push(`| ${schema.title} | ${rites.map(rite => results[rite.id].find(item => item.serviceId === schema.id).level).join(' | ')} |`);
for (const rite of rites) {
  md.push('', `## ${rite.title}`, '');
  for (const result of results[rite.id]) {
    md.push(`### ${result.title} — ${result.level}`);
    if (result.gap) md.push(`- Source gap: ${result.gap}`);
    for (const problem of result.problems) md.push(`- ${problem}`);
    if (result.absent?.length) md.push(`- Required concepts absent: ${result.absent.join(', ')}`);
    if (result.unknownCaptions?.length) md.push(`- Captions the day engine does not know yet: ${result.unknownCaptions.map(item => `«${item}»`).join(' · ')}`);
    for (const item of result.conditionsPending || []) md.push(`- Conditions pending: ${item}`);
    md.push('');
  }
}
const csv = ['nusach,service,order,section,concept,title,source_ref,paragraphs,when,role,required,omitted,verified'];
for (const rite of rites) for (const result of results[rite.id]) for (const section of result.sections) {
  csv.push([rite.id, result.serviceId, section.order, section.id, section.concept || '', section.title || '', section.ref, section.error ? 'ERROR' : `${section.from}-${section.to}`, section.when || '', section.role || '', section.required, section.omit, result.level === COMPLETENESS.VERIFIED].map(value => `"${String(value).replace(/"/g, '""')}"`).join(','));
}
const audit = ['# Siddur text audit', '', `Generated by scripts/siddur-qa.mjs on ${new Date().toISOString().slice(0, 10)}. Each finding names the exact address in the pack (paragraph index from 0) and the words. Nothing is repaired silently: display rules are listed in docs/siddur/text-corrections.md.`, ''];
for (const rite of rites) {
  const findings = audits[rite.id];
  const byCode = findings.reduce((map, item) => map.set(item.code, [...(map.get(item.code) || []), item]), new Map());
  audit.push(`## ${rite.title} — ${findings.length} findings`, '', '| Check | Count |', '|---|---:|', ...[...byCode].map(([code, items]) => `| ${items[0].label} (${code}) | ${items.length} |`), '');
  for (const [code, items] of byCode) {
    audit.push(`### ${items[0].label} (${code})`, '');
    for (const item of items.slice(0, 60)) audit.push(`- ${item.ref} ¶${item.index}: ${item.excerpt}`);
    if (items.length > 60) audit.push(`- … and ${items.length - 60} more`);
    audit.push('');
  }
}
if (!only) {
  mkdirSync(new URL('../docs/siddur/', import.meta.url), { recursive: true });
  writeFileSync(new URL('../docs/siddur/siddur-qa.md', import.meta.url), md.join('\n') + '\n');
  writeFileSync(new URL('../docs/siddur/content-table.csv', import.meta.url), csv.join('\n') + '\n');
  writeFileSync(new URL('../docs/siddur/text-audit.md', import.meta.url), audit.join('\n') + '\n');
}
if (!quiet) {
  for (const rite of rites) for (const result of results[rite.id]) if (COMPOSITIONS[rite.id]?.services?.[result.serviceId]) {
    console.log(`\n${rite.id} / ${result.serviceId}: ${result.level}`);
    for (const problem of result.problems) console.log(`  ✗ ${problem}`);
    if (result.absent.length) console.log(`  absent: ${result.absent.join(', ')}`);
    if (result.unknownCaptions.length) console.log(`  unknown captions: ${result.unknownCaptions.join(' · ')}`);
  }
  console.log('\n' + rites.map(rite => `${rite.id}: ${audits[rite.id].length} text findings`).join('\n'));
}
